spring.application.name=management-system
spring.datasource.url= ${DB_URL:jdbc:postgresql://localhost:5432/bug-tracking-system}
spring.datasource.username=  ${DB_USERNAME:postgres}
spring.datasource.password= ${DB_PASSWORD:Work@1234567890}
spring.datasource.driver-class-name= org.postgresql.Driver

server.port = 9988